juego:
	javac -g Juego.java

pikinims:
	javac -g Pikinim.java Amarillo.java Cyan.java Magenta.java

zonas:
	javac -g Zona.java Ilevantable.java Pieza.java Pildora.java Muralla.java Enemigo.java

run: pikinims zonas juego
	java Juego

clean:
	rm -rf *.class